site_name: JabRef - Teste
repo_url: https://antoonioaldisio.github.io/jabref/
theme:
  name: material
  language: pt

docs_dir: docs/

nav:
    - Sobre: 'index.md'
    - Configuraçōes: 'conf.md'
    - Testes Unidade:
      - Teste de unidade do JabRef: 'v01.md'
      - Testes de unidade da classe PdfAnnotationImporter: 'v02.md'
